package ink.tuanzi.flatlib.bukkit;

import org.bukkit.entity.Entity;

public class EntityUtil {

    /**
     * Check if it is an NPC.
     */
    public static <T extends Entity> boolean isNPC(T entity) {
        return isCitizensNPC(entity) || isShopKeepers(entity);
    }

    /**
     * Checks for NPC generated by the Citizens plugin.
     *
     * <p>
     * <a href="https://wiki.citizensnpcs.co/Citizens_Wiki">Citizens</a> plugin.
     * </p>
     *
     * @param entity An entity
     * @return is Citizens NPC?
     */
    public static <T extends Entity> boolean isCitizensNPC(T entity) {
        return entity.hasMetadata("NPC");
    }

    /**
     * Checks for NPC generated by the Shopkeepers plugin.
     * <p>
     * Generated by the <a href="https://github.com/Shopkeepers/Shopkeepers">Shopkeepers</a> plugin.
     * </p>
     *
     * @param entity An entity
     * @return is Shopkeepers NPC?
     */
    public static <T extends Entity> boolean isShopKeepers(T entity) {
        return entity.hasMetadata("shopkeeper");
    }
}
